##The website title
name: Techie Notes
##Markdown processor
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
##syntax highlighter. change it to pygments
highlighter: rouge #pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: https://dimus.github.io
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Blog about programming, devops and life
##Some frequently used keywords on your website
keywords: golang ruby chef docker linux devops

##define this for disqus comment support
disqus: dimus

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  email: dmozzherin@gmail.com
  github: dimus

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: dimus.jpg
##comment this if you want full width posts with no sidebar
sidebar: on

timezone: "America/New York"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
